In [19]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [20]:
df = pd.read_csv('insurance.csv')
df


age  affordability  insurance
0     22              1          0
1     25              0          0
2     47              1          1
3     52              0          0
4     46              1          1
..   ...            ...        ...
495   26              0          0
496   58              0          0
497   40              0          0
498   49              1          1
499   33              0          0

[500 rows x 3 columns]

In [21]:
df.head()

age  affordability  insurance
0   22              1          0
1   25              0          0
2   47              1          1
3   52              0          0
4   46              1          1

***split train and test***

In [22]:
x_train,x_test,y_train,y_test = train_test_split(df[['age','affordability']], df.insurance,test_size= 0.2,random_state= 25)

***scaling***

In [23]:
x_train_scaled =x_train.copy()
x_train_scaled['age']= x_train_scaled['age'] /100

In [24]:
x_test_scaled =x_test.copy()
x_test_scaled['age']= x_test_scaled['age'] /100

***model building in keras***

In [25]:
#kernel= weights
#input_shape= instances/columns

model = keras.Sequential([keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones',bias_initializer='zeros')])

C:\Users\ANQ\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


***compiling***

In [26]:
model.compile(optimizer='adam', loss= 'binary_crossentropy',metrics=['accuracy'])

In [27]:
model.fit(x_train_scaled,y_train, epochs=5000)

Epoch 1/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4960 - loss: 0.8198  
Epoch 2/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5009 - loss: 0.8310 
Epoch 3/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5152 - loss: 0.8109 
Epoch 4/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4991 - loss: 0.8062 
Epoch 5/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5319 - loss: 0.7726 
Epoch 6/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5309 - loss: 0.7866 
Epoch 7/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5260 - loss: 0.7586  
Epoch 8/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5583 - loss: 0.7390 
Epoch 9/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.5257 - loss: 0.7554
Epoch 10/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4907 - loss: 0.7824 
Epoch 11/5000
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5178 - loss: 0.7713 
Epoch 12/5000
13/13 ━━━━━━━━━━━━━━━━━━

***Evalute the model on test data***

In [30]:
model.evaluate(x_test_scaled,y_test)



4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5116 - loss: 0.6885  


[0.6952883005142212, 0.49000000953674316]

In [31]:
model.predict(x_test_scaled)
y_test

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


411    1
380    0
38     0
254    0
234    0
      ..
135    1
282    1
48     0
176    0
133    1
Name: insurance, Length: 100, dtype: int64

***now get the values of weights and bias from the model***

In [32]:
#coef is for weights, intercept is for bias

coef, intercept= model.get_weights()
coef, intercept

(array([[1.3448464 ],
        [0.02408864]], dtype=float32),
 array([-0.4819671], dtype=float32))

-------this means w1=1.344, w2=0.0256, bias= -0.48166...

***designing neural network without using any library***


In [40]:
def sigmoid(x):
    import math
    return 1/ (1+ math.exp(-x))
sigmoid(18)
# x is age

0.9999999847700205

In [46]:
#coff[0] represnets weight 1 and coff[1] represents weight 2

def prediction_function(age, affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability +intercept
    return sigmoid(weighted_sum)
#age is in points bcz its scaled value
prediction_function(.47, 1)


C:\Users\ANQ\AppData\Local\Temp\ipykernel_3412\1094292981.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/ (1+ math.exp(-x))


0.5434400407086551

In [47]:
prediction_function(.18, 1)

C:\Users\ANQ\AppData\Local\Temp\ipykernel_3412\1094292981.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/ (1+ math.exp(-x))


0.4462568922984417

***strat implementing the gradient descent.(back propogation)***

first write couple of helper routines such as sigmoid and log loss

In [152]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
    
sigmoid_numpy(np.array([12,0,1]))   

array([0.99999386, 0.5       , 0.73105858])

In [153]:
# calculating cost


def log_loss(y_true, y_ptrediction):
    epsilon  = 1e-15                                                                         #acting as threshold
    
    #applying if value of prediction is not equal to 0 or 1
    
    y_predicted_new = [max(i,epsilon) for i in y_predicted]                                  # value must be greater than epsilon or 0
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new] 
    y_predicted_new = np.array(y_predicted_new)                                              # put values in array
    return -np.mean(y_true*np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))   #log to solve issues/error(just simply apply it dont ask)

***implement our own custom neural network class***

In [154]:
# define class 
class myNN:
   
  def __init__(self):                                                        # costructor ( for constructor 'self' is used 
      
     self.w1 = 1                                 
     self.w2 = 1
     self.bias = 0
 
  def fit(self, X, y, epochs, loss_thresold):                                 # epochs is num of iterations,x are age and afodability,y is insurance
                                                                              #loss threshold to stop
     self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
     print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")

In [155]:
def predict(self, x_test):
    weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
    return sigmoid_numpy(weighted_sum)

In [174]:
def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):        #y_true is actual value
   w1 = w2 = 1                                                                     
   bias = 0
   rate = 0.5                                                                         #learning rate 
   n = len(age)                                                                       
   for i in range(epochs):                                                             #epochs is training data 
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)                                             #formula = (y_pred - y_act)^2
        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))                            # weight 1 update for age
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))                  #weight 2 for affordability ...transpose calculate chang
        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d 
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d                                                        
 
        if i%50==0:
             print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
 
        if loss<=loss_thresold:
              print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        break
   return w1, w2, bias
   customModel = myNN()
   customModel.fit(x_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)
   coef, intercept
   customModel.predict(X_test_scaled)     #(1) Predict using custom model

(2) Predict using tensorflow model

In [167]:
model.predict(x_test_scaled)


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step


array([[0.59289014],
       [0.5139892 ],
       [0.5072681 ],
       [0.58311665],
       [0.5574456 ],
       [0.46292722],
       [0.5407989 ],
       [0.4863972 ],
       [0.53675914],
       [0.48303825],
       [0.5541253 ],
       [0.52000433],
       [0.47632524],
       [0.44362912],
       [0.5139892 ],
       [0.52741385],
       [0.5072681 ],
       [0.56407046],
       [0.53006506],
       [0.56006885],
       [0.4870988 ],
       [0.5772494 ],
       [0.5407989 ],
       [0.58706313],
       [0.49984232],
       [0.58311665],
       [0.49984232],
       [0.50656617],
       [0.58964014],
       [0.5772494 ],
       [0.5106292 ],
       [0.5805279 ],
       [0.5574456 ],
       [0.5407989 ],
       [0.53006506],
       [0.46362546],
       [0.50656617],
       [0.4803818 ],
       [0.46962076],
       [0.53006506],
       [0.45624697],
       [0.56337976],
       [0.59356785],
       [0.57656395],
       [0.45958528],
       [0.48373955],
       [0.53675914],
       [0.513